# global config

chat-filter: false
filter-words:
   - пиздец
   - хуй
   - бля
   - блять
   - бл
   - хуета
   - хуйня
   - нахуй
   - ебал
   - съебал
   - ебаный
   - ёбаный
   - хуесос
   - трахал
   - трахнуть
   - трахну
   - обьебаный
   - ебучий
   - выебать
   - дебиан
   - уёбок
