name: ButtonSimulator
author: Zoga_com
version: 0.1
description: "жесть))"
main: ru.zoga_com.essentials.Main
softdepend: [Vault]


commands: 
  balance:
    permission: simulator.button.balance
    permission-message: 'Нет прав (simulator.button.balance)'
    description: 'баланс'
  sellall:
    permission: simulator.button.sellall
    permission-message: 'Нет прав (simulator.button.sellall)'
    description: 'продажа'
  util:
    permission: simulator.button.util
    permission-message: Нет прав (simulator.button.util)'
    description: 'утил'
  level:
    permission: simulator.button.level
    permission-message: Нет прав (simulator.button.level)'
    description: 'уровни'