name: MiniEssentials
author: Zoga_com
version: "1.0-patch2"
description: "EssentialsX, but my..."
main: ru.zoga_com.essentials.Main
softdepend: [Vault]


commands: 
  fly:
    permission: miniess.fly
    permission-message: 'Нет прав (miniess.fly)'
    description: 'полет'
  gm:
    permission: miniess.gamemode
    permission-message: 'Нет прав (miniess.gamemode)'
    description: 'гм'
  ping:
    permission: miniess.ping
    permission-message: 'Нет прав (miniess.ping)'
    description: 'пинг'